### ISSUE TITLE
node 0.6: TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by gboudreau** [rknLA/irc-slack-echo#8]
Was using node 0.6.x; was getting this error:

```
gb@iwebtwo:~/irc-slack-echo $ node .

util.js:511
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (util.js:511:43)
    at Object.<anonymous> (/home/gb/irc-slack-echo/node_modules/hapi/node_modules/shot/lib/index.js:64:6)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/gb/irc-slack-echo/node_modules/hapi/node_modules/shot/index.js:1:80)
    at Module._compile (module.js:446:26)
```

Might be worth describing in the doc what version of node is required; not sure which is really required, but updating to latest (0.10.28) fixed that issue for me.

**Comment by gboudreau** [comment]
Thanks.
